language: ruby

rvm:
  - 2.0.0

# Using faster container based build environment.
sudo: false

services:
  - mongodb

notifications:
  slack:
    secure: WiknGrMbu8llQc6tG6cf0y8ZOmTVtmtzJhlW2NGQwdqEJdvTt5N7KuIBifOXboYnWIo4AjCO9VN8QHHlFdTRysgb0ZIfQO3aG6aLqwn2LgDqm3qa1z6EKaL8wQx10ZErAJQD82dB0F0BjOeuqpPWsm+ZWIkK+9iT9TPBoQwMzgE=

deploy:
  provider: openshift
  user: l33tname@outlook.com
  password:
    secure: hynlswjwK9D62Z02TcWB9qQDHvx5hyF4rTuRz65PMPSIKuRCdbjGbrSAZlrdzwD3SzHBP7V3fU1Ku/euqElGzlenETNELE/LtCXLxgKUqwq4lzL5X1ljuyA3KD97ex2eFjcdCCur7YzgzAYSbRr9rGl5dHZtn68zOC89yJ0mACM=
  app: whichfoodisbetter
  domain: l33tname
  on:
    repo: optikfluffel/what-food-is-worse 

